[project]
name = "expense-tracker"
version = "0.1.0"
description = "A simple expense tracker for personal use."
authors = [
    {name = "Ilya Kutilin",email = "ilyakutilin@yandex.ru"}
]
license = "MIT"
readme = "../README.md"
requires-python = ">=3.14,<4.0"
dependencies = [
    "fastapi[standard-no-fastapi-cloud-cli] (>=0.121.1,<0.122.0)",
    "pydantic-settings (>=2.12.0,<3.0.0)",
    "alembic (>=1.17.1,<2.0.0)",
    "asyncpg (>=0.30.0,<0.31.0)",
    "sqlalchemy (>=2.0.44,<3.0.0)",
    "loguru (>=0.7.3,<0.8.0)",
    "passlib[bcrypt] (>=1.7.4,<2.0.0)",
    "python-jose[cryptography] (>=3.5.0,<4.0.0)",
    "python-multipart (>=0.0.21,<0.0.22)",
    "bcrypt (>=4,<5)",
    "redis[hiredis] (>=7.1.0,<8.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false
