"""Initial migration

Revision ID: bcafc871a766
Revises: 
Create Date: 2025-12-08 17:03:16.894460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcafc871a766'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True, start=1, increment=1, cycle=False), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currency_is_deleted'), 'currency', ['is_deleted'], unique=False)
    op.create_index('ix_currency_unique_code_active', 'currency', ['code'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('tag',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True, start=1, increment=1, cycle=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_is_deleted'), 'tag', ['is_deleted'], unique=False)
    op.create_index('ix_tag_unique_name_active', 'tag', ['name'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('account',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True, start=1, increment=1, cycle=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('currency_id', sa.BigInteger(), nullable=True),
    sa.Column('balance', sa.Numeric(precision=23, scale=8, decimal_return_scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_currency_id'), 'account', ['currency_id'], unique=False)
    op.create_index(op.f('ix_account_is_deleted'), 'account', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_account_parent_id'), 'account', ['parent_id'], unique=False)
    op.create_index(op.f('ix_account_type'), 'account', ['type'], unique=False)
    op.create_index('ix_account_unique_name_active', 'account', ['name'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('operation',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True, start=1, increment=1, cycle=False), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('from_acc_id', sa.BigInteger(), nullable=False),
    sa.Column('to_acc_id', sa.BigInteger(), nullable=False),
    sa.Column('from_amount', sa.Numeric(precision=23, scale=8, decimal_return_scale=8), nullable=False),
    sa.Column('to_amount', sa.Numeric(precision=23, scale=8, decimal_return_scale=8), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_template', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_acc_id'], ['account.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_acc_id'], ['account.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_comment'), 'operation', ['comment'], unique=False)
    op.create_index(op.f('ix_operation_date'), 'operation', ['date'], unique=False)
    op.create_index(op.f('ix_operation_from_acc_id'), 'operation', ['from_acc_id'], unique=False)
    op.create_index(op.f('ix_operation_is_deleted'), 'operation', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_operation_is_template'), 'operation', ['is_template'], unique=False)
    op.create_index(op.f('ix_operation_to_acc_id'), 'operation', ['to_acc_id'], unique=False)
    op.create_index(op.f('ix_operation_type'), 'operation', ['type'], unique=False)
    op.create_table('operation_tag',
    sa.Column('operation_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operation.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('operation_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation_tag')
    op.drop_index(op.f('ix_operation_type'), table_name='operation')
    op.drop_index(op.f('ix_operation_to_acc_id'), table_name='operation')
    op.drop_index(op.f('ix_operation_is_template'), table_name='operation')
    op.drop_index(op.f('ix_operation_is_deleted'), table_name='operation')
    op.drop_index(op.f('ix_operation_from_acc_id'), table_name='operation')
    op.drop_index(op.f('ix_operation_date'), table_name='operation')
    op.drop_index(op.f('ix_operation_comment'), table_name='operation')
    op.drop_table('operation')
    op.drop_index('ix_account_unique_name_active', table_name='account', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_account_type'), table_name='account')
    op.drop_index(op.f('ix_account_parent_id'), table_name='account')
    op.drop_index(op.f('ix_account_is_deleted'), table_name='account')
    op.drop_index(op.f('ix_account_currency_id'), table_name='account')
    op.drop_table('account')
    op.drop_index('ix_tag_unique_name_active', table_name='tag', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_tag_is_deleted'), table_name='tag')
    op.drop_table('tag')
    op.drop_index('ix_currency_unique_code_active', table_name='currency', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_currency_is_deleted'), table_name='currency')
    op.drop_table('currency')
    # ### end Alembic commands ###
