"""Soft delete

Revision ID: 9c05c595a651
Revises: 92ecf07a9f84
Create Date: 2025-12-05 14:30:02.827530

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9c05c595a651'
down_revision: Union[str, Sequence[str], None] = '92ecf07a9f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('account', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_account_name'), table_name='account')
    op.create_index(op.f('ix_account_is_deleted'), 'account', ['is_deleted'], unique=False)
    op.create_index('ix_account_unique_name_active', 'account', ['name'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.add_column('currency', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('currency', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_currency_code'), table_name='currency')
    op.create_index(op.f('ix_currency_is_deleted'), 'currency', ['is_deleted'], unique=False)
    op.create_index('ix_currency_unique_code_active', 'currency', ['code'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.add_column('operation', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('operation', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_operation_is_deleted'), 'operation', ['is_deleted'], unique=False)
    op.add_column('tag', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('tag', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.create_index(op.f('ix_tag_is_deleted'), 'tag', ['is_deleted'], unique=False)
    op.create_index('ix_tag_unique_name_active', 'tag', ['name'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tag_unique_name_active', table_name='tag', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_tag_is_deleted'), table_name='tag')
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    op.drop_column('tag', 'deleted_at')
    op.drop_column('tag', 'is_deleted')
    op.drop_index(op.f('ix_operation_is_deleted'), table_name='operation')
    op.drop_column('operation', 'deleted_at')
    op.drop_column('operation', 'is_deleted')
    op.drop_index('ix_currency_unique_code_active', table_name='currency', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_currency_is_deleted'), table_name='currency')
    op.create_index(op.f('ix_currency_code'), 'currency', ['code'], unique=True)
    op.drop_column('currency', 'deleted_at')
    op.drop_column('currency', 'is_deleted')
    op.drop_index('ix_account_unique_name_active', table_name='account', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_account_is_deleted'), table_name='account')
    op.create_index(op.f('ix_account_name'), 'account', ['name'], unique=True)
    op.drop_column('account', 'deleted_at')
    op.drop_column('account', 'is_deleted')
    # ### end Alembic commands ###
