"""Split Transaction

Revision ID: 70dd4f91f9b3
Revises: 8f9fac1bf281
Create Date: 2025-12-22 17:04:12.975335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70dd4f91f9b3'
down_revision: Union[str, Sequence[str], None] = '8f9fac1bf281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True, start=1, increment=1, cycle=False), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_template', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_comment'), 'transaction', ['comment'], unique=False)
    op.create_index(op.f('ix_transaction_date'), 'transaction', ['date'], unique=False)
    op.create_index(op.f('ix_transaction_is_deleted'), 'transaction', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_transaction_is_template'), 'transaction', ['is_template'], unique=False)
    op.create_index(op.f('ix_transaction_type'), 'transaction', ['type'], unique=False)
    op.create_table('transaction_tag',
    sa.Column('transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('transaction_id', 'tag_id')
    )
    op.create_table('transaction_line',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True, start=1, increment=1, cycle=False), nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=23, scale=8, decimal_return_scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transaction_line_account_date', 'transaction_line', ['account_id', 'transaction_id'], unique=False)
    op.create_index(op.f('ix_transaction_line_account_id'), 'transaction_line', ['account_id'], unique=False)
    op.create_index(op.f('ix_transaction_line_is_deleted'), 'transaction_line', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_transaction_line_transaction_id'), 'transaction_line', ['transaction_id'], unique=False)
    op.drop_table('operation_tag')
    op.drop_index(op.f('ix_operation_comment'), table_name='operation')
    op.drop_index(op.f('ix_operation_date'), table_name='operation')
    op.drop_index(op.f('ix_operation_from_acc_id'), table_name='operation')
    op.drop_index(op.f('ix_operation_is_deleted'), table_name='operation')
    op.drop_index(op.f('ix_operation_is_template'), table_name='operation')
    op.drop_index(op.f('ix_operation_to_acc_id'), table_name='operation')
    op.drop_index(op.f('ix_operation_type'), table_name='operation')
    op.drop_table('operation')
    op.drop_column('account', 'balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('balance', sa.NUMERIC(precision=23, scale=8), autoincrement=False, nullable=True))
    op.create_table('operation',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('from_acc_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('to_acc_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('from_amount', sa.NUMERIC(precision=23, scale=8), autoincrement=False, nullable=False),
    sa.Column('to_amount', sa.NUMERIC(precision=23, scale=8), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_template', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['from_acc_id'], ['account.id'], name='operation_from_acc_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_acc_id'], ['account.id'], name='operation_to_acc_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='operation_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_operation_type'), 'operation', ['type'], unique=False)
    op.create_index(op.f('ix_operation_to_acc_id'), 'operation', ['to_acc_id'], unique=False)
    op.create_index(op.f('ix_operation_is_template'), 'operation', ['is_template'], unique=False)
    op.create_index(op.f('ix_operation_is_deleted'), 'operation', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_operation_from_acc_id'), 'operation', ['from_acc_id'], unique=False)
    op.create_index(op.f('ix_operation_date'), 'operation', ['date'], unique=False)
    op.create_index(op.f('ix_operation_comment'), 'operation', ['comment'], unique=False)
    op.create_table('operation_tag',
    sa.Column('operation_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operation.id'], name=op.f('operation_tag_operation_id_fkey')),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('operation_tag_tag_id_fkey')),
    sa.PrimaryKeyConstraint('operation_id', 'tag_id', name=op.f('operation_tag_pkey'))
    )
    op.drop_index(op.f('ix_transaction_line_transaction_id'), table_name='transaction_line')
    op.drop_index(op.f('ix_transaction_line_is_deleted'), table_name='transaction_line')
    op.drop_index(op.f('ix_transaction_line_account_id'), table_name='transaction_line')
    op.drop_index('ix_transaction_line_account_date', table_name='transaction_line')
    op.drop_table('transaction_line')
    op.drop_table('transaction_tag')
    op.drop_index(op.f('ix_transaction_type'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_is_template'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_is_deleted'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_date'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_comment'), table_name='transaction')
    op.drop_table('transaction')
    # ### end Alembic commands ###
