"""Account balance related indexes

Revision ID: c80f410ceb92
Revises: 1d72ce203acf
Create Date: 2026-01-28 23:36:09.175930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c80f410ceb92'
down_revision: Union[str, Sequence[str], None] = '1d72ce203acf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_transaction_user_active', 'transaction', ['user_id', 'id'], unique=False, postgresql_where=sa.text('(is_deleted = false) AND (is_template = false)'))
    op.drop_index(op.f('ix_transaction_line_account_date'), table_name='transaction_line')
    op.create_index('ix_transaction_line_account_transaction', 'transaction_line', ['account_id', 'transaction_id'], unique=False, postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transaction_line_account_transaction', table_name='transaction_line', postgresql_where=sa.text('is_deleted = false'))
    op.create_index(op.f('ix_transaction_line_account_date'), 'transaction_line', ['account_id', 'transaction_id'], unique=False)
    op.drop_index('ix_transaction_user_active', table_name='transaction', postgresql_where=sa.text('(is_deleted = false) AND (is_template = false)'))
    # ### end Alembic commands ###
