"""Relationships to user

Revision ID: 63866b4babd2
Revises: 45fff6864881
Create Date: 2026-01-12 15:07:41.398676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63866b4babd2'
down_revision: Union[str, Sequence[str], None] = '45fff6864881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.drop_index(op.f('ix_account_unique_name_active'), table_name='account', postgresql_where='(is_deleted = false)')
    op.create_index('ix_account_unique_name_per_user_active', 'account', ['user_id', 'name'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_index(op.f('ix_account_user_id'), 'account', ['user_id'], unique=False)
    op.create_foreign_key(None, 'account', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('currency', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.drop_index(op.f('ix_currency_unique_code_active'), table_name='currency', postgresql_where='(is_deleted = false)')
    op.create_index('ix_currency_unique_code_per_user_active', 'currency', ['user_id', 'code'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_index(op.f('ix_currency_user_id'), 'currency', ['user_id'], unique=False)
    op.create_foreign_key(None, 'currency', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('tag', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.drop_index(op.f('ix_tag_unique_name_active'), table_name='tag', postgresql_where='(is_deleted = false)')
    op.create_index('ix_tag_unique_name_per_user_active', 'tag', ['user_id', 'name'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_index(op.f('ix_tag_user_id'), 'tag', ['user_id'], unique=False)
    op.create_foreign_key(None, 'tag', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('transaction', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_transaction_user_id'), 'transaction', ['user_id'], unique=False)
    op.create_foreign_key(None, 'transaction', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_index(op.f('ix_transaction_user_id'), table_name='transaction')
    op.drop_column('transaction', 'user_id')
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_index(op.f('ix_tag_user_id'), table_name='tag')
    op.drop_index('ix_tag_unique_name_per_user_active', table_name='tag', postgresql_where=sa.text('is_deleted = false'))
    op.create_index(op.f('ix_tag_unique_name_active'), 'tag', ['name'], unique=True, postgresql_where='(is_deleted = false)')
    op.drop_column('tag', 'user_id')
    op.drop_constraint(None, 'currency', type_='foreignkey')
    op.drop_index(op.f('ix_currency_user_id'), table_name='currency')
    op.drop_index('ix_currency_unique_code_per_user_active', table_name='currency', postgresql_where=sa.text('is_deleted = false'))
    op.create_index(op.f('ix_currency_unique_code_active'), 'currency', ['code'], unique=True, postgresql_where='(is_deleted = false)')
    op.drop_column('currency', 'user_id')
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_index(op.f('ix_account_user_id'), table_name='account')
    op.drop_index('ix_account_unique_name_per_user_active', table_name='account', postgresql_where=sa.text('is_deleted = false'))
    op.create_index(op.f('ix_account_unique_name_active'), 'account', ['name'], unique=True, postgresql_where='(is_deleted = false)')
    op.drop_column('account', 'user_id')
    # ### end Alembic commands ###
