"""Require user id

Revision ID: 66c1c5adf5a0
Revises: 6a97c0db2025
Create Date: 2026-01-22 11:48:49.026207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66c1c5adf5a0'
down_revision: Union[str, Sequence[str], None] = '6a97c0db2025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(op.f('account_user_id_fkey'), 'account', type_='foreignkey')
    op.create_foreign_key(None, 'account', 'user', ['user_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('currency', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(op.f('currency_user_id_fkey'), 'currency', type_='foreignkey')
    op.create_foreign_key(None, 'currency', 'user', ['user_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('tag', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(op.f('tag_user_id_fkey'), 'tag', type_='foreignkey')
    op.create_foreign_key(None, 'tag', 'user', ['user_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('transaction', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(op.f('transaction_user_id_fkey'), 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'user', ['user_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_user_id_fkey'), 'transaction', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('transaction', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.create_foreign_key(op.f('tag_user_id_fkey'), 'tag', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('tag', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(None, 'currency', type_='foreignkey')
    op.create_foreign_key(op.f('currency_user_id_fkey'), 'currency', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('currency', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.create_foreign_key(op.f('account_user_id_fkey'), 'account', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('account', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
