"""Transaction date nullable

Revision ID: 1d72ce203acf
Revises: 66c1c5adf5a0
Create Date: 2026-01-28 11:18:24.164024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d72ce203acf'
down_revision: Union[str, Sequence[str], None] = '66c1c5adf5a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
